title: Lior Fox
url: "https://liorfox.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: 'Jekyll template design adapted from <a target="_blank" style="color: black" href="https://github.com/ankitsultana/researcher">researcher</a> theme'

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "pubs"
 - name: "Teaching"
   link: "teaching"
 - name: 'Blogposts and other'
   link: 'other'

plugins:
  - jekyll-target-blank